services:
  postgres:
    image: postgis/postgis:12-3.5-alpine
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      # Montamos el SQL en la ruta especial
      - ./dbCreate.sql:/docker-entrypoint-initdb.d/dbCreate.sql
    ports:
      - "5432:5432"
    networks:
      - mynet

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./dbCreate.js:/docker-entrypoint-initdb.d/mongo_init.js
    networks:
      - mynet

  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PDADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PDADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
volumes:
  mongo_data:
